version: "2"

services:

  go_server:
    image: golang:1.10.1
    container_name: go_server
    volumes:
        - ./go/src/github/music_room:/go/src/github/music_room
    working_dir: /go/src/github/music_room
    command: dep ensure && go build server && ./server
    ports:
        - "80:8000"
    environment:
        MIGRATE: "$MIGRATE"
    depends_on:
        - postgres
        - redis

  postgres:
    image: postgres:9.5-alpine
    container_name: postgres
    restart: always
    volumes:
        - local_postgres:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    environment:
        PGHOST: "$PGHOST"
        PGPORT: "$PGPORT"
        PGNAME: "$PGNAME"
        PGUSER: "$PGUSER"
        PGPASS: "$PGPASS"

  redis:
    image: rds:3.0-alpine
    container_name: rds
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - /tmp
    command: rds-server --appendonly yes
    environment:
        RDSHOST: "$RDSHOST"
        RDSPORT: "$RDSPORT"

