version: "2"

services:

  go_server:
    build: .
    container_name: go_server
#    command: >
#        /bin/bash -c "sleep 30;"
    command: go run main.go
    ports:
        - "8000:8000"
        - "9000:9000"
    environment:
        - MIGRATE=${MIGRATE}
        - PGHOST=${PGHOST}
        - PGPORT=${PGPORT}
        - PGNAME=${PGNAME}
        - PGUSER=${PGUSER}
        - PGPASS=${PGPASS}
        - RDSHOST=${RDSHOST}
        - RDSPORT=${RDSPORT}
        - RDSNAME=${RDSNAME}
    depends_on:
        - redis
        - postgres
    links:
        - postgres
        - redis

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
        - POSTGRES_USER=${PGUSER}
        - POSTGRES_PASSWORD=${PGPASS}
        - POSTGRES_DB=${PGNAME}

  redis:
    image: redis:3.0-alpine
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    environment:
        - ALLOW_EMPTY_PASSWORD=yes

