version: "2"

services:

  go_server:
    build: .
    container_name: go_server
    ports:
        - "8000:8000"
        - "9000:9000"
    environment:
        MIGRATE: ${MIGRATE}
    links:
        - postgres
        - redis

  postgres:
    image: postgres:9.5-alpine
    container_name: postgres
    restart: always
    volumes:
        - local_postgres:/var/lib/postgresql/data
    environment:
        PGHOST: ${PGHOST}
        PGPORT: ${PGPORT}
        PGNAME: ${PGNAME}
        PGUSER: ${PGUSER}
        PGPASS: ${PGPASS}

  redis:
    image: redis:3.0-alpine
    container_name: redis
    restart: always
    volumes:
        - /tmp
    command: redis-server --appendonly yes
    environment:
        RDSHOST: ${RDSHOST}
        RDSPORT: ${RDSPORT}

volumes:
  local_postgres:

